# school_project/data.py

students_data = [
    {
        "id": 1,
        "FirstName": "أحمد",
        "LastName": "الهاشمي",
        "Age": 21,
        "Gender": "ذكر",
        "Level": "السنة الثالثة",
        "Status": "نعم",
    },
    {
        "id": 2,
        "FirstName": "محمد",
        "LastName": "الحضرمي",
        "Age": 22,
        "Gender": "ذكر",
        "Level": "السنة الرابعة",
        "Status": "نعم",
    },
    {
        "id": 3,
        "FirstName": "ليلى",
        "LastName": "الشريف",
        "Age": 19,
        "Gender": "أنثى",
        "Level": "السنة الأولى",
        "Status": "نعم",
    },
    {
        "id": 4,
        "FirstName": "فهد",
        "LastName": "القاسمي",
        "Age": 23,
        "Gender": "ذكر",
        "Level": "السنة الخامسة",
        "Status": "لا",
    },
    {
        "id": 5,
        "FirstName": "سارة",
        "LastName": "الزهري",
        "Age": 20,
        "Gender": "أنثى",
        "Level": "السنة الثانية",
        "Status": "نعم",
    },
    {
        "id": 6,
        "FirstName": "عبدالله",
        "LastName": "النعيمي",
        "Age": 24,
        "Gender": "ذكر",
        "Level": "السنة الخامسة",
        "Status": "لا",
    },
    {
        "id": 7,
        "FirstName": "مريم",
        "LastName": "العسيري",
        "Age": 18,
        "Gender": "أنثى",
        "Level": "السنة الأولى",
        "Status": "نعم",
    },
    {
        "id": 8,
        "FirstName": "خالد",
        "LastName": "المري",
        "Age": 22,
        "Gender": "ذكر",
        "Level": "السنة الرابعة",
        "Status": "نعم",
    },
    {
        "id": 9,
        "FirstName": "هدى",
        "LastName": "القرشي",
        "Age": 21,
        "Gender": "أنثى",
        "Level": "السنة الثالثة",
        "Status": "نعم",
    },
    {
        "id": 10,
        "FirstName": "بدر",
        "LastName": "التميمي",
        "Age": 23,
        "Gender": "ذكر",
        "Level": "السنة الخامسة",
        "Status": "لا",
    },
]

teachers_data = [
    {
        "id": 1,
        "FirstName": "علي",
        "LastName": "المالكي",
        "Age": 45,
        "Gender": "ذكر",
        "Subject": "الرياضيات",
        "Status": "نعم",
    },
    {
        "id": 2,
        "FirstName": "فاطمة",
        "LastName": "الشمراني",
        "Age": 38,
        "Gender": "أنثى",
        "Subject": "اللغة العربية",
        "Status": "نعم",
    },
    {
        "id": 3,
        "FirstName": "يوسف",
        "LastName": "الدوسري",
        "Age": 50,
        "Gender": "ذكر",
        "Subject": "الفيزياء",
        "Status": "لا",
    },
    {
        "id": 4,
        "FirstName": "نورة",
        "LastName": "السبيعي",
        "Age": 32,
        "Gender": "أنثى",
        "Subject": "الكيمياء",
        "Status": "نعم",
    },
    {
        "id": 5,
        "FirstName": "ماجد",
        "LastName": "القحطاني",
        "Age": 48,
        "Gender": "ذكر",
        "Subject": "تاريخ",
        "Status": "نعم",
    },
]
